language: node_js

node_js:
    - '10'

env:
    - DIRTY_SNAPSHOTS=0

cache:
    npm: false

addons:
    hosts:
        - localhost.paypal.com

before_install:
    - npm i -g npm@6

before_script:
    - if [[ "${DIRTY_SNAPSHOTS}" = "0" ]] || [[ "${TRAVIS_BRANCH}" = "develop" ]]; then npm run dev:standalone; fi &

script:
    - npm run lint
    - npm run test
    - ./scripts/snapshot-tests/run-tests.sh

deploy:
    provider: script
    skip_cleanup: true
    script:
        - npx semantic-release
    on:
        branch: release
