name: Snapshot Tests

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Check for trigger commit
              run: ./scripts/snapshot-tests/should-update.sh
            - name: Use Node.js 10.x
              if: env.UPDATE_SNAPSHOT != 1
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: Run snapshot tests
              if: env.UPDATE_SNAPSHOT != 1
              run: |
                  ./scripts/snapshot-tests/setup-tests.sh
                  npm run test:func
              env:
                  CI: true
